cache:
    event:
        - $SD_SOURCE_DIR/node_modules
    pipeline:
        - ~/.gradle
    job:
        test-job: [/tmp/testblah]
jobs:
    test-job:
        image: node:6
        steps:
            - env: env
            - ls-tmp: ls /tmp
            - ls-gradle: ls /root
            - ls-node: ls
            - echo: echo hi > /tmp/testblah
    npm1:
        image: node:6
        steps:
            - install: npm install
    npm2:
        image: node:6
        steps:
            - ls: ls
            - install: npm install
        requires: [npm1]
    gradle:
        image: java:7
        steps:
            - ls: ls ~/
            - install: git clone https://github.com/gradle-guides/gradle-site-plugin.git && cd gradle-site-plugin && ./gradlew build
